name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --no-scripts --quiet
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Wait for MySQL to be ready
      run: |
        until nc -z -v -w30 localhost 3306
        do
          echo "Waiting for MySQL..."
          sleep 5
        done
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: convertedin_db
        DB_USERNAME: dev
        DB_PASSWORD: dev
      run: php artisan test

    services:
      mysql:
        image: mysql:8
        container_name: convertedin_mysql
        env:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: convertedin_db
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=10s --health-retries=5
